name: Docker Image CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get the version and commit info
      id: vars
      run: |
        git describe --tags
        git describe --tag
        echo "::set-output name=VERSION::$(git describe --tags)"
        echo "::set-output name=COMMIT_ID::$(git rev-parse HEAD)"
    - name: Build the Docker image
      run: |
        docker build . \
        --build-arg VERSION=${{ steps.vars.outputs.VERSION }} \
        --build-arg COMMIT_ID=${{ steps.vars.outputs.COMMIT_ID }} \
        --file Dockerfile \
        --tag chonla/umock:${{ steps.vars.outputs.VERSION }}
