name: Docker Image CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get the version and commit info
      id: vars
      run: |
        echo "::set-output name=VERSION::$(cat VERSION)"
        echo "::set-output name=COMMIT_ID::$(git rev-parse --short HEAD)"
    - name: Authenticate to docker
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the docker image
      run: |
        docker build . \
        --build-arg VERSION=${{ steps.vars.outputs.VERSION }} \
        --build-arg COMMIT_ID=${{ steps.vars.outputs.COMMIT_ID }} \
        --file Dockerfile \
        --tag chonla/umock:${{ steps.vars.outputs.VERSION }} \
        --tag chonla/umock:latest
    - name: Store docker images
      run: |
        docker push chonla/umock --all-tags
